elastic-query-service:
  version: v1
  custom-audience: elastic-query-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/gelenler-tutorial
  jpa:
    open-in-view: false
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
    username: keycloak
    password: '{cipher}1f1c2d807682cfed8604459dd74615a1e80713d53179ba7d3a1166eece8dd256'
  sql:
    init:
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      mode: always

server:
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text
  use-repository: true

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connection-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: art
  password: '{cipher}f131e75d110494eb27823d8d6652f5a9d63bfa86e438d7f5dbe322b79493e79a'
  roles:
    - USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
security:
  paths-to-ignore: /api-docs