elastic-query-service:
  back-pressure-delay-ms: 500

elastic-query-config:
  text-field: text
  use-repository: true

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connection-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: art
  password: '{cipher}f131e75d110494eb27823d8d6652f5a9d63bfa86e438d7f5dbe322b79493e79a'
  roles:
    - USER

spring:
  webflux:
    base-path: /reactive-elastic-query-service
  codec:
    max-in-memory-size: 25MB
  elasticsearch:
    webclient:
      max-in-memory-size: 25MB
    uris: ${elastic-config.connection-url}
#  data:
#    elasticsearch:
#      client:
#        reactive:
#          max-in-memory-size: 25MB
