### Get default client configuration
GET http://localhost:8080/config-client/default
Accept: application/json
Authorization: Basic c3ByaW5nX2Nsb3VkX3VzZXI6c3ByaW5nQ2xvdWRfUHdkIQ==

### Get twitter_to_kafka client configuration
GET http://localhost:8080/config-client/twitter_to_kafka
Accept: application/json
Authorization: Basic c3ByaW5nX2Nsb3VkX3VzZXI6c3ByaW5nQ2xvdWRfUHdkIQ==