twitter-to-kafka-service:
  welcome-message: Welcome to twitter-to-kafka-service
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}




