version: '3.8'

volumes:
  keycloak_postgres_data:
    driver: local

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  adminer:
    image: adminer
    profiles:
      - debug
    restart: always
    ports:
      - 9082:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres:5432
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  # Open http://localhost:8181/admin and login as user 'admin' with password 'Pa55w0rd'.
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    command:
      - "start-dev --import-realm"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - 8181:8080
    depends_on:
      - postgres
    networks:
      - ${GLOBAL_NETWORK:-elastic}
    volumes:
      - ./export:/opt/keycloak/data/import:ro
#      - ./export-gelenler:/opt/keycloak/data/import:ro
