version: '3'
services:

  twitter-to-kafka-service:
    image: ${GROUP_ID}/art-gelenler-twitter-to-kafka-service:${SERVICE_VERSION:-latest}
    ports:
      - "8091:8091"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: ["check-config-server-started.sh"]
    depends_on:
      - config-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_NET_SHYSHKIN_STUDY=debug"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY_URL=http://schema-registry:8081"
      - "TWITTER-TO-KAFKA-SERVICE_MOCK_ENABLE=true"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8080"
    networks:
      - ${GLOBAL_NETWORK:-services}

  config-server:
    image: ${GROUP_ID}/art-gelenler-config-server:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n -Xms128m -Xmx256m"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_PROFILES_ACTIVE=separate-remote-git-repo"
      - "GITHUB_ACCESS_TOKEN={cipher}43c0c0b04ad14146b1da3870650c6b39506c4763a53276eab40e47b9422fc6ef4a68e2bb44267abd6b39d73af9fce4bd9902b3638038526fac51dae2f00a7e53"
    networks:
      - ${GLOBAL_NETWORK:-services}


