server.port: 8091
spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  cloud:
    config:
#      fail-fast: true
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8080
      username: spring_cloud_user
      password: springCloud_Pwd!
  config:
    import: 'configserver:'