server.port: 8091
spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  cloud:
    config:
#      fail-fast: true
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8080
      username: spring_cloud_user
      password: ENC(U6CPf8pQwZn4NjfUqedtFjDaqYAjfXfoflZlEztinXsT/KAKpUH8hdl4jpov9hoOkuixqGhzM5mqwsRB96QP7Q==)
  config:
    import: 'configserver:'

jasypt:
  encryptor:
    password: plain_jasypt_password_not_recommended
