twitter-to-kafka-service:
  welcome-message: Welcome to twitter-to-kafka-service
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  mock:
    enable: true
    tweet-length:
      min: 5
      max: 15
    sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.4
  max-attempts: 3
  sleep-time-ms: 2000



