### Get Open API 3.0 documentation
GET http://localhost:8093/elastic-query-service/api-docs
Accept: application/json

### Get Open API 3.0 documentation as YAML file
GET http://localhost:8093/elastic-query-service/api-docs.yaml
Authorization: Basic art artPassword

### Open Swagger UI with Basic Auth
GET http://localhost:8093/elastic-query-service/swagger-ui.html
Authorization: Basic art artPassword