### Healthcheck
GET http://localhost:8093/elastic-query-service/actuator/health
Accept: application/json

### Get All documents
GET http://localhost:8093/elastic-query-service/documents
Accept: application/json
#Authorization: Basic YXJ0OmFydFBhc3N3b3Jk
Authorization: Basic art artPassword

### Get document by id
GET http://localhost:8093/elastic-query-service/documents/1
Accept: application/json
#Authorization: Basic YXJ0OmFydFBhc3N3b3Jk
Authorization: Basic art artPassword

### Search for document by text
POST http://localhost:8093/elastic-query-service/documents/get-document-by-text
Accept: application/json
Content-Type: application/json
Authorization: Basic art artPassword

{
  "id": null,
  "userId": null,
  "text": "Microservices",
  "createdAt": null
}

###



