server.port: 8194

spring:
  application:
    name: elastic-query-web-client-2

---
spring:
  config:
    activate:
      on-profile: configserver
    import: 'configserver:'
  cloud:
    config:
#      fail-fast: true
      name: ${spring.application.name}
      uri: http://localhost:8080
      username: spring_cloud_user
      password: '{cipher}d0bb54467b358c6a4f2aecbdca486be7d41c0f81df2b5dd9c722b41888e7fe8f85240138e768ddeeef3ade2144534a9a'

#encrypt:
#  key: ${ENCRYPT_KEY}
