logging:
  level:
    ROOT: info
    org.springframework.cloud.config: debug

server:
  port: 8080

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #with common git repository - disadvantage - clone all the repo with submodules (longer)
          uri: @project.basedir@/../
          default-label: main
          search-paths: config-server-repository
          basedir: ${user.home}/config-repo
          clone-on-start: true
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!

---
spring:
  config:
    activate:
      on-profile: remote-git-repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/artshishkin/art-gelenler-event-driven
          default-label: main
          search-paths: config-server-repository
          basedir: ${user.home}/config-repo
          clone-on-start: true
      fail-fast: true

---
spring:
  config:
    activate:
      on-profile: separate-remote-git-repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/artshishkin/art-gelenler-event-driven-config-repo
          default-label: main
          search-paths: '{config-client}'
          basedir: ${user.home}/config-repo-remote
          clone-on-start: true
          username: artshishkin
          password: ${GITHUB_ACCESS_TOKEN:fake}
      fail-fast: true

---
spring:
  config:
    activate:
      on-profile: separate-git-repo-locally
      #with separate git repository `config-server-repository` (git init)
  cloud:
    config:
      server:
        git:
          #          uri: file:C:\Users\Admin\IdeaProjects\Study\AliGelenler\art-gelenler-event-driven\config-server-repository #gives Could not merge error
          #          uri: C:\Users\Admin\IdeaProjects\Study\AliGelenler\art-gelenler-event-driven\config-server-repository #works
          uri: @project.basedir@\..\config-server-repository
          default-label: master
          search-paths: '{config-client}'
