# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tested on JVM 17 (MacOS)

on:
  push:
    branches: [ main, mac-fabric8-conflict, docker-caching ]
  pull_request:
    branches: [ main ]

jobs:
  build-java17-mac:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
      - run: set -x
      - name: Print Docker version
        run: docker --version
#      - name: Pull docker images
#        run: |
#          docker pull docker.elastic.co/elasticsearch/elasticsearch:7.17.3
#          docker pull quay.io/keycloak/keycloak:19.0.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - run: mkdir -p ~/image-cache

      - id: image-cache
        uses: actions/cache@v3
        with:
          path: ~/image-cache
          # Adjust key to meet your cache time requirements e.g.
          # ${{ hashFiles(*) }} can be useful here to invalidate
          # cache on file changes
          key: docker-cache-${{ runner.os }}-${{ hashFiles( 'docker-compose/.env' ) }}

      - if: steps.image-cache.outputs.cache-hit != 'true'
        name: Pull docker images
        run: |
          docker pull docker.elastic.co/elasticsearch/elasticsearch:7.17.3
          docker save -o ~/image-cache/elasticsearch.tar docker.elastic.co/elasticsearch/elasticsearch:7.17.3
          docker pull quay.io/keycloak/keycloak:19.0.1
          docker save -o ~/image-cache/keycloak.tar quay.io/keycloak/keycloak:19.0.1

      - if: steps.image-cache.outputs.cache-hit == 'true'
        name: Restore docker images from cache
        run: |
          docker load -i ~/image-cache/elasticsearch.tar
          docker load -i ~/image-cache/keycloak.tar

#      - name: Cache local Maven repository
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
